import pandas as pd
df=pd.read_csv(filepath_or_buffer="C://mydataset//tips.csv")
# df=df=pd.read_csv(filepath_or_buffer="C://mydataset//tips.csv",usecols=['total_bill','tip'])
# df=pd.read_csv(filepath_or_buffer="C://mydataset//tips.csv",skiprows=10)
print(df)
print(df.shape)
print(df.memory_usage())
print(df.info())
sunday_customer=df.loc[df['day']=='Sun']
tips=df.groupby(['sex','day']).sum()
count_sex_smokers=df.groupby(['sex','smoker'])['smoker'].count()
smokers_nonsmokers=df['smoker'].value_counts(normalize=True)
df['mes']=df['size'].apply(lambda x:"Large" if x>=3 else "Small")
print(sunday_customer.describe())
print(tips)
print(count_sex_smokers)
print(smokers_nonsmokers)
print(df[:20])
print(df)
